import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState,parsePressure,transition,observePressure,transmitPressure,selectPressure,measurementChain,displayPressure} from '../public/assets/js/simulations/gas-metering-pressure-model.js';
const tuple=s=>{const c=measurementChain(s);return [c.processPa,c.observation.valuePa,c.transmitted.valuePa,c.selected.valuePa];};
const bias=s=>transition(s,{type:'bias',enabled:true}).state;
const apply=(s,text)=>transition(s,{type:'apply',text}).state;
const good=valuePa=>({valuePa,quality:'GOOD',unit:'Pa',basis:'absolute'});
test('pressure: initial unbiased chain',()=>assert.deepEqual(tuple(initialState()),[300000,300000,300000,300000]));
test('pressure: bias changes observation, never process or prior state',()=>{const s=Object.freeze(initialState());assert.deepEqual(tuple(bias(s)),[300000,320000,320000,320000]);assert.deepEqual(s,initialState());});
test('pressure: apply 250 with bias then remove bias',()=>{const s=apply(bias(initialState()),'250');assert.deepEqual(tuple(s),[250000,270000,270000,270000]);assert.deepEqual(tuple(transition(s,{type:'bias',enabled:false}).state),[250000,250000,250000,250000]);});
test('pressure: boundary observations are not clamped',()=>{assert.deepEqual(tuple(bias(apply(initialState(),'200'))),[200000,220000,220000,220000]);assert.deepEqual(tuple(bias(apply(initialState(),'400'))),[400000,420000,420000,420000]);});
test('pressure: parse explicit whole kPa and surrounding whitespace',()=>assert.deepEqual(parsePressure(' 250 '),{valuePa:250000}));
test('pressure: invalid drafts retain exact accepted state',()=>{const s=bias(initialState());for(const text of ['', ' ', '250.0','2e2','2,50','250 kPa','250x','199','401','NaN','Infinity',NaN,Infinity,null,undefined,250,'-250','+250']){const result=transition(s,{type:'apply',text});assert.equal(result.state,s,String(text));assert.ok(result.error);assert.deepEqual(tuple(s),[300000,320000,320000,320000]);}});
test('pressure: communication uses supplied observation, not process/default',()=>{const o=good(287000);assert.deepEqual(transmitPressure(o),o);assert.notEqual(transmitPressure(o),o);});
test('pressure: FC uses supplied transmission',()=>assert.deepEqual(selectPressure(good(333000)),{...good(333000),source:'PT'}));
test('pressure: missing/unavailable current input never retains prior selection',()=>{selectPressure(good(333000));for(const x of [undefined,null,{quality:'UNAVAILABLE',valuePa:333000}]){assert.equal(selectPressure(x).valuePa,null);assert.equal(selectPressure(x).quality,'UNAVAILABLE');}});
test('pressure: invalid data fails closed at each boundary',()=>{for(const x of [{},good(NaN),good(Infinity),good('300000'),good(0),good(421000),good(300001),{...good(300000),basis:'gauge'},{...good(300000),unit:'kPa'},{...good(300000),quality:'INVALID'}]){for(const fn of [transmitPressure,selectPressure]){assert.equal(fn(x).valuePa,null);assert.equal(fn(x).quality,'INVALID');}assert.equal(displayPressure(x),'—');}});
test('pressure: malformed process cannot create valid observation',()=>{for(const p of [NaN,Infinity,null,undefined,'300000',199000,401000,300001])assert.equal(observePressure(p,false).quality,'INVALID');});
test('pressure: biased valid observation remains GOOD',()=>{const c=measurementChain(bias(initialState()));for(const r of [c.observation,c.transmitted,c.selected])assert.equal(r.quality,'GOOD');});
test('pressure: reset is deterministic and returns fresh state',()=>{const s=apply(bias(initialState()),'400');assert.deepEqual(transition(s,{type:'reset'}),{state:initialState(),error:null});assert.notEqual(initialState(),initialState());});
test('pressure: equivalent actions produce identical states',()=>{assert.deepEqual(apply(bias(initialState()),'250'),bias(apply(initialState(),'250')));});
test('pressure: display includes basis and unit, invalid output is absent',()=>{assert.equal(displayPressure(good(420000)),'420 kPa (absolute)');assert.equal(displayPressure(undefined),'—');});
