import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {TRAINING_MODULES as modules,QUESTION_BANK as bank,QUESTION_AUDIT,auditQuestionBank,PRACTICALS,trainingRead,trainingSource} from '../public/assets/js/simulations/oxymitter-4000/training-data.mjs';
import {createTrainingEngine,SCORING} from '../public/assets/js/simulations/oxymitter-4000/training-engine.mjs';
const root=new URL('../',import.meta.url);
function knowledge(t,wrong=false){t.start();for(const q of bank){t.submit(wrong?q.choices.find(c=>c.id!==q.correctAnswer).id:q.correctAnswer);t.next();}}
function startup(t){t.act('power');t.act('warm');t.next();}
const calibration=['manual','verify','start','apply1','enter','advance','apply2','enter','advance','remove','enter','advance','automatic'];
function cal(t){for(const a of calibration)t.act(a);t.next();}
function diag(t){for(const a of ['blink','blink','fault-2'])t.act(a);t.next();}
function trouble(t){for(const a of ['T19-trend','safe','Inspection / source review','next','T19','safe','T19-action'])t.act(a);t.next();}
function complete(wrong=false){const t=createTrainingEngine();knowledge(t,wrong);startup(t);cal(t);diag(t);trouble(t);return t;}
test('M5 six modules and four bounded practicals have direct sources',()=>{assert.equal(modules.length,6);assert.equal(PRACTICALS.length,4);for(const m of modules){assert.ok(m.objective&&m.interaction);for(const d of m.facts){trainingRead(d);assert.match(trainingSource(d),/Rev AE.*PDF p/);}}for(const p of PRACTICALS)for(const d of p.sources)trainingRead(d);});
test('M5 stable question IDs and assessment domain coverage',()=>{assert.deepEqual(bank.map(q=>q.id),Array.from({length:15},(_,i)=>`OX-Q${String(i+1).padStart(2,'0')}`));for(const m of modules)assert.ok(bank.some(q=>q.module===m.id));});
test('M5 every correct choice is the audited supported answer',()=>{assert.deepEqual(QUESTION_AUDIT,{questions:15,SUPPORTED:74,DERIVED:0,UNSUPPORTED:0});for(const q of bank)assert.deepEqual(q.choices.find(c=>c.id===q.correctAnswer).datum,q.answer);});
for(const status of ['DERIVED','UNSUPPORTED'])test(`M5 audit rejects ${status} correct answer`,()=>{const b=structuredClone(bank);b[0].answer={status,availability:'BLOCKED',gapId:'TEST',reason:'Blocked',source:b[0].answer.source};assert.throws(()=>auditQuestionBank(b));});
test('M5 audit rejects wrong evidence, mappings and duplicate IDs',()=>{for(const mutation of [b=>b[0].answer.source.evidenceId='NOPE',b=>b[0].correctAnswer='missing',b=>b[0].choices[0].id=b[0].choices[1].id,b=>b[1].id=b[0].id]){const b=structuredClone(bank);mutation(b);assert.throws(()=>auditQuestionBank(b));}});
test('M5 lessons require interaction then a correct submitted check',()=>{const t=createTrainingEngine(),m=modules[0],q=bank.find(q=>q.id===m.question);assert.throws(()=>t.lessonAnswer(m.id,q.correctAnswer));t.lessonInteract(m.id);t.lessonAnswer(m.id,q.choices.find(c=>c.id!==q.correctAnswer).id);assert.equal(t.snapshot().lessons[m.id].complete,false);t.lessonAnswer(m.id,q.correctAnswer);assert.equal(t.snapshot().lessons[m.id].complete,true);});
test('M5 active question snapshot conceals answer/source until submission',()=>{const t=createTrainingEngine();t.start();const s=t.snapshot();assert.equal(s.feedback,null);assert.equal(s.question.correctAnswer,undefined);assert.equal(s.question.source,undefined);assert.equal(s.result,null);t.submit(bank[0].correctAnswer);assert.equal(t.snapshot().feedback.correct,true);assert.ok(t.snapshot().feedback.source.evidenceId);});
test('M5 first submitted answer is final for that attempt',()=>{const t=createTrainingEngine();t.start();assert.throws(()=>t.next());assert.throws(()=>t.submit('unknown'));t.submit(bank[0].choices.find(c=>c.id!==bank[0].correctAnswer).id);assert.throws(()=>t.submit(bank[0].correctAnswer));assert.equal(t.snapshot().feedback.correct,false);});
test('M5 no lesson or retry bypass during active assessment',()=>{const t=createTrainingEngine();t.start();assert.throws(()=>t.start());assert.throws(()=>t.lessonInteract('startup'));});
test('M5 startup practical calls source engine and requires ordered actions',()=>{const t=createTrainingEngine();knowledge(t);assert.equal(t.snapshot().practical.status,'POWER OFF');assert.throws(()=>t.act('warm'));t.act('power');assert.equal(t.snapshot().practical.status,'WARM UP');t.act('warm');assert.equal(t.snapshot().practical.status,'NORMAL OPERATION');assert.equal(t.snapshot().practical.errors,1);assert.equal(t.snapshot().practical.done,true);});
test('M5 calibration practical requires purge and AUTOMATIC for completion',()=>{const t=createTrainingEngine();knowledge(t);startup(t);for(const a of calibration.slice(0,-1))t.act(a);assert.equal(t.snapshot().practical.done,false);assert.equal(t.snapshot().cleanupRequired,true);assert.throws(()=>t.reset());t.act('automatic');assert.equal(t.snapshot().practical.done,true);assert.equal(t.snapshot().cleanupRequired,false);});
test('M5 wrong calibration action changes educational errors only',()=>{const t=createTrainingEngine();knowledge(t);startup(t);const before=t.snapshot().practical.status;assert.throws(()=>t.act('apply2'));assert.equal(t.snapshot().practical.status,before);assert.equal(t.snapshot().practical.errors,1);});
test('M5 aborted calibration still requires cleanup and earns no point',()=>{const t=createTrainingEngine();knowledge(t);startup(t);for(const a of ['manual','verify','start','abort'])t.act(a);assert.throws(()=>t.reset());for(const a of ['remove','advance','automatic'])t.act(a);t.next();diag(t);trouble(t);assert.equal(t.snapshot().result.practicals.find(p=>p.id==='calibration').correct,false);assert.equal(t.snapshot().result.practicalCompleted,3);});
test('M5 diagnostic practical steps documented pause then identifies exact fault',()=>{const t=createTrainingEngine();knowledge(t);startup(t);cal(t);assert.throws(()=>t.act('fault-2'));t.act('blink');t.act('blink');assert.match(t.snapshot().practical.status,/Pause 2 seconds/);assert.match(t.snapshot().practical.observation,/O2 T\/C Shorted/);assert.throws(()=>t.act('fault-1'));t.act('fault-2');assert.equal(t.snapshot().practical.done,true);});
test('M5 troubleshooting requires check, safety, observation, diagnosis and corrective action',()=>{const t=createTrainingEngine();knowledge(t);startup(t);cal(t);diag(t);t.act('T19-trend');assert.throws(()=>t.act('Inspection / source review'));assert.match(t.snapshot().practical.status,/TEST/);t.act('safe');t.act('Inspection / source review');assert.match(t.snapshot().practical.observation,/smoother trend/);t.act('next');t.act('T19');assert.throws(()=>t.act('T19-action'));t.act('safe');t.act('T19-action');assert.equal(t.snapshot().practical.done,true);});
test('M5 perfect result is deterministic 19 points with module breakdown',()=>{const r=complete().snapshot().result;assert.equal(r.points,19);assert.equal(r.correct,15);assert.equal(r.practicalCompleted,4);assert.equal(r.breakdown.length,6);assert.deepEqual(r.weak,[]);assert.deepEqual(complete().snapshot().result,r);});
test('M5 weak modules and answer review preserve learner and correct answers',()=>{const r=complete(true).snapshot().result;assert.equal(r.points,4);assert.equal(r.correct,0);assert.equal(r.weak.length,6);for(const a of r.answers)assert.notEqual(a.choice,a.question.correctAnswer);});
test('M5 retry clears assessment scores and preserves completed lessons',()=>{const t=complete();t.lessonInteract('startup');t.lessonAnswer('startup',bank.find(q=>q.id==='OX-Q06').correctAnswer);t.start();assert.equal(t.snapshot().result,null);assert.equal(t.snapshot().index,0);assert.equal(t.snapshot().attempt,2);assert.equal(t.snapshot().lessons.startup.complete,true);});
test('M5 explicit educational reset clears progress and scores',()=>{const t=complete();t.reset();assert.equal(t.snapshot().mode,'IDLE');assert.deepEqual(t.snapshot().lessons,{});assert.equal(t.snapshot().result,null);});
test('M5 scoring is educational and has no pass/certification threshold',()=>{assert.equal(SCORING.threshold,null);assert.equal(SCORING.classification,'educational infrastructure');assert.match(SCORING.disclaimer,/educational simulator only/);});
test('M5 has no storage, network, backend or autonomous physical simulation',()=>{for(const file of ['training-data.mjs','training-engine.mjs','ui/training-page.mjs']){const s=readFileSync(new URL('public/assets/js/simulations/oxymitter-4000/'+file,root),'utf8');assert.doesNotMatch(s,/localStorage|sessionStorage|indexedDB|document\.cookie|fetch\(|XMLHttpRequest|firebase|firestore|setInterval|setTimeout/);}});
test('M5 reset/navigation guards preserve inherited calibration cleanup',()=>{const s=readFileSync(new URL('public/assets/js/simulations/oxymitter-4000/ui/training-page.mjs',root),'utf8');assert.match(s,/c\.active\|\|c\.needsAutomatic/);assert.match(s,/stopImmediatePropagation/);assert.match(s,/s\.cleanupRequired/);});
test('M5 M7 route exists in public source',()=>{assert.equal(existsSync(new URL('public/simulations/oxymitter-4000/',root)),true);});
test('M5 prior engines, fixtures and reports retain hashes; migrated tests match reviewed M7 hashes',()=>{const files={"docs/27-oxymitter-4000-m1.md": "469a8310a62698e994afb86e4d078e7e1cfd982596a08a07f6d843a3a4e288f5", "docs/28-oxymitter-4000-m2.md": "72778e78dd4e5337e6b5ccc30febd5e08bfcf47123cf5c8b3794507758062393", "docs/29-oxymitter-4000-m3.md": "fcf37626ff0e47cebe235f7365df9dc9f32d5eef32a82ff5bc403e85cefeb435", "docs/30-oxymitter-4000-m4.md": "dee0ae1c297fd9ae07e1eb55b2f08358984da8811c84515938014c2cc8bf0f9e", "public/assets/js/simulations/oxymitter-4000/calibration-data.mjs": "736eed329da1b688e79c02cae92133f4be4c85aa8b52c1a48b557f1c0af87a9a", "public/assets/js/simulations/oxymitter-4000/calibration-engine.mjs": "d14e54e61f524d2c1b1778d8693f295029f54d266ce2081ed8fce65261f9cf2b", "public/assets/js/simulations/oxymitter-4000/ui/diagnostic-page.mjs": "52479fbc02bbba0b60be1d7a28c6271f1b3dac04317f47d075818814136b8238", "public/assets/js/simulations/oxymitter-4000/ui/page.mjs": "40cc0922a2ff30db0cc5b48b3be9647c674f00aac33eb96b0dd485071aa0b801", "public/assets/js/simulations/oxymitter-4000/ui/view-model.mjs": "dd84adf2c52b948de66038a309fa4e712212b6dd3ba6ae755022b66ed4ce5f3f", "public/assets/js/simulations/oxymitter-4000/diagnostic-data.mjs": "3e402ae2dc730854bc7edf87b7e190c0d4f4532963b7140f366f84d6a0541def", "public/assets/js/simulations/oxymitter-4000/diagnostic-engine.mjs": "d11879fbdb9b9609c3d771672db6f4720aa4f8a712cb6866e06c7938b0fb4b3c", "public/assets/js/simulations/oxymitter-4000/provenance.mjs": "f99c17fecef7c081f94621ec0de101cd6a54a7966e5b3dfdb1b41519f1a278ed", "public/assets/js/simulations/oxymitter-4000/source-data.mjs": "d9afe6d622387020d749e171147cbc1e10c3984ad041f65213966e196fa4288d", "public/assets/js/simulations/oxymitter-4000/startup-engine.mjs": "54f623974074f3a9f11e157da915e3499eec38fb065cde26fe8ba4018566aac6", "site-tests/oxymitter-4000-m2-browser.mjs": "d321b8f933ea82f81fb2f627116a418da1cc8a7268ba5209f1f9054e50405625", "site-tests/oxymitter-4000-m2.test.mjs": "958207036c74db5ac0fc496a7a2fd93e3b1a00839dab90614d9f67f1742478d3", "site-tests/oxymitter-4000-m3-browser.mjs": "93fb2ba7071085ac7e5766ca256b6978dd6c368178177d3aec64b5dcc64572b3", "site-tests/oxymitter-4000-m3.test.mjs": "0ab22f478a203996e3988ca479774e7d290b6ecef91ad6810562ae4f69f61a70", "site-tests/oxymitter-4000-m4-browser.mjs": "2a715eeab8858828772dee39341deff2d26213aaa1f24382fd003a3c6e0584bf", "site-tests/oxymitter-4000-m4.test.mjs": "43a4e73778cb618c5cd2380023ceb27a21b2467c8fdab87f0bd259bb79a4da89", "site-tests/oxymitter-4000.test.mjs": "cdf7dee315adbff3514e83a1e6750c0ef71fbc8d43c0ef0f397d29742a7d3a0d"};for(const [path,hash]of Object.entries(files))assert.equal(createHash('sha256').update(readFileSync(new URL(path,root))).digest('hex'),hash,path);});

test('M5 practical review retains rejected actions and source-backed expected sequence',()=>{const t=createTrainingEngine();knowledge(t);assert.throws(()=>t.act('warm'));startup(t);cal(t);diag(t);trouble(t);const p=t.snapshot().result.practicals[0];assert.equal(p.transcript[0].accepted,false);assert.match(p.transcript[0].message,/documented startup/);assert.equal(p.documentedPath.length,2);assert.ok(p.sources.every(d=>d.status==='SUPPORTED'));assert.equal(p.correct,false);});
