#!/usr/bin/env node
/* =========================================================
   InstMates – Technology hub generator (W1.3)

   Renders /public/technology/<slug>/index.html from the canonical
   hub model (taxonomy.js + content-map.js). Only terms whose
   taxonomy entry declares a published `hub` route are rendered;
   the output is committed so Hosting stays static. site-tests
   re-render and compare, so the HTML can never drift from the model.

   Usage:  node scripts/build-hub.mjs            (writes every published hub)
           node scripts/build-hub.mjs --check    (exit 1 if any file differs)
========================================================= */
import { writeFileSync, readFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { TERMS, termBySlug } from "../public/assets/js/taxonomy.js";
import { hubModel, HUB_SECTIONS } from "../public/assets/js/content-map.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://www.instmates.com";

const KIND_LABEL = Object.freeze({
  overview: "Overview", explanation: "Explanation", components: "Components", fault: "Failure modes",
  troubleshooting: "Troubleshooting", calibration: "Calibration", sampling: "Sampling", case: "Case study",
  reference: "Reference", blog: "Article", index: "Index"
});

/** Evidence-based intro copy per published hub (no counts hard-coded: counts come from the model). */
const INTRO = Object.freeze({
  "gas-chromatography": "Process gas chromatography as it is installed, sampled, run and repaired in the plant: how a GC separates and measures, what the valves, columns and detectors do, how it fails, how the sample gets to it, and documented cases from real analyzer shelters."
});

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const pad = (n) => String(n).padStart(2, "0");

export function publishedTerms() {
  return TERMS.filter((t) => t.hub);
}

export function renderHub(slug) {
  const term = termBySlug(slug);
  const hub = hubModel(slug);
  if (!term || !hub || !hub.published || !hub.eligible) throw new Error(`hub not publishable: ${slug}`);
  const url = `${SITE}${term.hub}`;
  const title = `${term.label} – Technical Hub | InstMates`;
  const description = `${term.label} on InstMates: ${hub.sections.map((s) => `${s.label.toLowerCase()} (${s.resources.length})`).join(", ")} – ${hub.resourceCount} real resources, plus discussions and how to contribute.`;
  const intro = INTRO[slug] || `${term.label} resources on InstMates.`;

  const sectionsHtml = hub.sections.map((s, i) => `
    <section class="hub-section" id="${s.id}" aria-labelledby="${s.id}-title">
      <div class="hub-section-head">
        <span class="hub-num" aria-hidden="true">${pad(i + 1)}</span>
        <h2 id="${s.id}-title">${esc(s.label)}</h2>
        <span class="hub-count">${s.resources.length} ${s.resources.length === 1 ? "resource" : "resources"}</span>
      </div>
      <ol class="hub-list">
${s.resources.map((r) => `        <li><a href="${esc(r.path)}"><span class="hub-kind">${esc(KIND_LABEL[r.kind] || r.kind)}</span><span class="hub-title">${esc(r.title)}</span></a></li>`).join("\n")}
      </ol>
    </section>`).join("\n");

  const breadcrumb = {
    "@type": "BreadcrumbList",
    "itemListElement": [
      { "@type": "ListItem", "position": 1, "name": "Home", "item": `${SITE}/` },
      { "@type": "ListItem", "position": 2, "name": term.label, "item": url }
    ]
  };
  const collection = {
    "@type": "CollectionPage",
    "@id": url,
    "name": `${term.label} technical hub`,
    "url": url,
    "description": description,
    "publisher": { "@type": "Organization", "name": "InstMates", "url": `${SITE}/` },
    "hasPart": hub.sections.flatMap((s) => s.resources.map((r) => ({ "@type": "WebPage", "name": r.title, "url": `${SITE}${r.path}` })))
  };
  const ld = JSON.stringify({ "@context": "https://schema.org", "@graph": [breadcrumb, collection] }, null, 2);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!-- GENERATED by scripts/build-hub.mjs from taxonomy.js + content-map.js (W1.3). Do not edit by hand:
     run  node scripts/build-hub.mjs  and commit the result. site-tests verify this file equals the model. -->
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}" />
<link rel="canonical" href="${url}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="${esc(title)}" />
<meta property="og:description" content="${esc(description)}" />
<meta property="og:url" content="${url}" />
<meta property="og:image" content="${SITE}/assets/images/home/hero-instrumentation.jpg" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(title)}" />
<meta name="twitter:description" content="${esc(description)}" />
<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48">
<link rel="icon" type="image/png" sizes="192x192" href="/assets/icons/instmates-192.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="#0b5ed7">
<link rel="stylesheet" href="/assets/css/style.css?v=2026-02-17">
<script type="application/ld+json">
${ld}
</script>
<!-- Technical-drawing direction, first restrained use (hub only): rule lines, numbered
     sections, monospace metadata. Scoped to .hub; no sitewide change. -->
<style>
.hub{--ink:#0b3c5d;--rule:#94a3b8;--mono:ui-monospace,"SFMono-Regular",Menlo,Consolas,monospace}
.hub-head{padding:22px 0 18px;border-bottom:2px solid var(--ink)}
.hub-kicker{font-family:var(--mono);font-size:.8rem;letter-spacing:.14em;text-transform:uppercase;color:var(--ink);margin:0 0 6px}
.hub h1{margin:0 0 10px;font-size:2rem;line-height:1.15}
.hub-intro{max-width:760px;line-height:1.55;margin:0 0 12px}
.hub-meta{display:flex;flex-wrap:wrap;gap:8px 18px;font-family:var(--mono);font-size:.85rem;color:#334155;margin:0;padding:0;list-style:none}
.hub-meta li::before{content:"■ ";color:var(--ink)}
.hub-toc{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0 0;padding:0;list-style:none}
.hub-toc a{display:inline-flex;align-items:center;min-height:44px;padding:6px 12px;border:1px solid var(--rule);border-radius:6px;font-family:var(--mono);font-size:.85rem;color:var(--ink);text-decoration:none;background:#fff}
.hub-toc a:hover{border-color:var(--ink)}
.hub-section{padding:20px 0 6px;border-top:1px solid var(--rule);scroll-margin-top:84px}
.hub-section-head{display:grid;grid-template-columns:auto 1fr auto;align-items:baseline;gap:12px;margin-bottom:10px}
.hub-num{font-family:var(--mono);font-size:.95rem;color:var(--ink);font-weight:700}
.hub-section h2{margin:0;font-size:1.3rem}
.hub-count{font-family:var(--mono);font-size:.8rem;color:#475569;white-space:nowrap}
.hub-list{list-style:none;margin:0;padding:0;display:grid;gap:8px}
.hub-list a{display:grid;grid-template-columns:118px 1fr;align-items:center;gap:12px;min-height:48px;padding:10px 12px;background:#fff;border:1px solid #d7dee8;border-left:3px solid var(--ink);border-radius:6px;color:#0f172a;text-decoration:none}
.hub-list a:hover{border-color:var(--ink)}
.hub-kind{font-family:var(--mono);font-size:.8rem;letter-spacing:.06em;text-transform:uppercase;color:#475569}
.hub-title{font-weight:600;line-height:1.3}
.hub-community{padding:20px 0 6px;border-top:1px solid var(--rule)}
.hub-empty{border:1px dashed var(--rule);border-radius:8px;padding:16px;background:#f8fafc}
.hub-empty p{margin:0 0 10px}
.hub-actions{display:flex;flex-wrap:wrap;gap:10px}
.hub-actions .btn{min-height:44px;display:inline-flex;align-items:center;justify-content:center;white-space:normal;text-align:center}
.hub .btn-primary{background:var(--ink);border:1px solid var(--ink);color:#fff}
.hub-posts{list-style:none;margin:0 0 12px;padding:0;display:grid;gap:10px}
.hub-posts li{border:1px solid #d7dee8;border-radius:6px;padding:10px 12px;line-height:1.45;background:#fff}
.hub-posts .hub-kind{margin-right:8px}
.hub-contribute{padding:20px 0 30px;border-top:2px solid var(--ink)}
.hub-contribute p{max-width:760px;line-height:1.5}
.hub a:focus-visible,.hub .btn:focus-visible{outline:3px solid #f59e0b;outline-offset:2px}
@media (max-width:768px){
  .hub h1{font-size:1.5rem}
  .hub-list a{grid-template-columns:1fr;gap:2px;padding:10px 12px}
  .hub-section-head{grid-template-columns:auto 1fr;grid-template-areas:"num title" "count count"}
  .hub-count{grid-area:count;margin-left:0}
  .hub-actions .btn{flex:1 1 100%}
}
@media (prefers-reduced-motion:reduce){.hub *{transition:none!important}}
</style>
</head>
<body data-page="technology">

<div id="siteHeader"></div>

<nav class="crumbs" aria-label="Breadcrumb">
  <a href="/">Home</a><span>›</span>
  <span class="current">${esc(term.label)}</span>
</nav>

<main class="container hub" id="main" data-hub="${esc(slug)}">

  <header class="hub-head">
    <p class="hub-kicker">Technology hub · ${esc(term.group || "analyzer")}</p>
    <h1>${esc(term.label)}</h1>
    <p class="hub-intro">${esc(intro)}</p>
    <ul class="hub-meta">
      <li>${hub.resourceCount} real resources</li>
      <li>${hub.sections.length} sections</li>
      <li>Sections appear only when content exists</li>
    </ul>
    <ul class="hub-toc" aria-label="Sections">
${hub.sections.map((s, i) => `      <li><a href="#${s.id}">${pad(i + 1)} ${esc(s.label)}</a></li>`).join("\n")}
      <li><a href="#community">${pad(hub.sections.length + 1)} Community</a></li>
      <li><a href="#contribute">${pad(hub.sections.length + 2)} Contribute</a></li>
    </ul>
  </header>
${sectionsHtml}

  <section class="hub-community" id="community" aria-labelledby="community-title">
    <div class="hub-section-head">
      <span class="hub-num" aria-hidden="true">${pad(hub.sections.length + 1)}</span>
      <h2 id="community-title">Community</h2>
      <span class="hub-count" data-hub-discussions-count></span>
    </div>
    <!-- hub.js fills this from the existing public latest-posts read, matched ONLY by
         canonical tags (normalizeTag). No tags today → the honest empty state stays. -->
    <ol class="hub-posts" data-hub-discussions hidden></ol>
    <div class="hub-empty" data-hub-empty>
      <p><strong>No ${esc(term.tag || term.label)} discussions yet.</strong> Discussions appear here when members tag a post with ${esc(term.tag || term.label)}.</p>
      <div class="hub-actions">
        <a class="btn btn-primary" href="/feed/?type=question">Ask the first question</a>
        <a class="btn btn-ghost" href="/feed/?type=fault">Share a field problem</a>
      </div>
    </div>
  </section>

  <section class="hub-contribute" id="contribute" aria-labelledby="contribute-title">
    <div class="hub-section-head">
      <span class="hub-num" aria-hidden="true">${pad(hub.sections.length + 2)}</span>
      <h2 id="contribute-title">Contribute</h2>
      <span class="hub-count">login to post</span>
    </div>
    <p>Worked on a ${esc(term.label.toLowerCase())} fault, fix or calibration? Post it in the feed with the ${esc(term.tag || term.label)} tag so it appears here.</p>
    <div class="hub-actions">
      <a class="btn btn-primary" href="/feed/?type=solution">Share a solution</a>
      <a class="btn btn-ghost" href="/feed/?type=calibration">Share calibration experience</a>
      <a class="btn btn-ghost" href="/profiles/">Browse public professionals</a>
      <a class="btn btn-ghost" href="/knowledge/">Knowledge Hub</a>
    </div>
  </section>

</main>

<div id="siteFooter"></div>

<script src="/assets/js/includes.js?v=2026-02-20"></script>
<script type="module" src="/assets/js/hub.js?v=2026-09-07"></script>

</body>
</html>
`;
}

export function hubFile(slug) {
  const term = termBySlug(slug);
  return path.join(ROOT, "public", ...term.hub.replace(/^\/|\/$/g, "").split("/"), "index.html");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  let drift = 0;
  for (const term of publishedTerms()) {
    const html = renderHub(term.slug);
    const file = hubFile(term.slug);
    if (check) {
      const current = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : "";
      if (current !== html) { drift++; console.error(`DRIFT: ${file}`); }
    } else {
      mkdirSync(path.dirname(file), { recursive: true });
      writeFileSync(file, html);
      console.log(`wrote ${path.relative(ROOT, file)} (${hubModel(term.slug).resourceCount} resources)`);
    }
  }
  if (check) { console.log(drift ? `${drift} hub file(s) drifted` : "hubs in sync"); process.exit(drift ? 1 : 0); }
}
